backend:
  name: github
  repo: skyfly200/Daniel-Vega-Site
  branch: master

public_folder: ".vuepress/dist/"
media_folder: ".vuepress/dist/assets/img"

display_url: https://daniel-vega.netlify.com

collections:
  - name: "page"
    label: "Pages"
    folder: "./"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
