backend:
  name: github
  repo: skyfly200/Daniel-Vega-Site
  branch: master

public_folder: ".vuepress/dist/"
media_folder: ".vuepress/dist/assets/img"

display_url: https://daniel-vega.netlify.com

collections:
  - name: "landing"
    label: "Home"
    files:
      - label: "Home"
        name: "home"
        file: "README.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Menu Icon", name: "menuIcon", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
  - name: "pages"
    label: "Pages"
    folder: "./"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Hide In Menu", name: "hideInMenu", widget: "boolean", default: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "sample"
    label: "Samples"
    folder: "sample"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Hide In Menu", name: "hideInMenu", widget: "boolean", default: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "works"
    label: "Works"
    folder: "works"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
