backend:
  name: github
  repo: skyfly200/Daniel-Vega-Site
  branch: master

public_folder: ".vuepress/dist/"
media_folder: ".vuepress/dist/assets"

display_url: https://daniel-vega.netlify.com

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "README.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Menu Icon", name: "menuIcon", widget: "string"}
          - {label: "Parallax Image", name: "parallaxImage", widget: "file"}
          - {label: "Parallax Header", name: "parallaxHeader", widget: "string"}
          - {label: "Parallax Content", name: "parallaxContent", widget: "text"}
          - {label: "Body", name: "body", widget: "markdown"}
      - label: "Bio"
        name: "bio"
        file: "bio.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Menu Icon", name: "menuIcon", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - label: "Contact"
        name: "contact"
        file: "contact.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Menu Icon", name: "menuIcon", widget: "string"}
          - {label: "Phone", name: "phone", widget: "string"}
          - {label: "Email", name: "email", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
  - name: "sample"
    label: "Samples"
    folder: "sample"
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "works"
    label: "Works"
    folder: "works"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Type", name: "workType", widget: "select", options: ["audio", "video", "youtube"]}
      - {label: "File", name: "file", widget: "file", optional: true}
      - {label: "ID", name: "id", widget: "string", optional: true}
      - {label: "Is a Playlist", name: "playlist", widget: "boolean"}
      - {label: "Embed Code", name: "raw", widget: "string", optional: true}
      - {label: "Body", name: "body", widget: "markdown", optional: true}
  - name: "events"
    label: "Events"
    folder: "events"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Event Url", name: "url", widget: "string"}
      - {label: "Group", name: "group", widget: "string"}
      - {label: "Group Url", name: "groupUrl", widget: "string"}
      - {label: "Venue", name: "venue", widget: "string"}
      - {label: "Venue Url", name: "venueUrl", widget: "string"}
      - {label: "Location", name: "location", widget: "string"}
      - {label: "Date and Time", name: "datetime", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "posts"
    label: "Blog Posts"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
